### ISSUE TITLE
Add a new function to play video on browser 

### ISSUE THREAD

**Issue by omi10859** [omi10859/PyouPlay#4]
For now, we have Two functions in total **toplink** gives the link for a video and **toplinks** gives top 20 links for a search on youtube. I want to add a new function that can play a video on the browser. 
ex: If you call that function with an argument(Youtube Search) it will play can video on browser.

For reference, there is a Python library which can help https://docs.python.org/3/library/webbrowser.html  

The file you need to edit 
https://github.com/omi10859/PyouPlay/blob/master/PyouPlay/get.py

After its working on your machine don't forget to update requirement of the project in setup.py

**Comment by TileThePlane** [comment]
Please assign to me, thanks.

**Comment by omi10859** [comment]
Start working. Waiting for your PR @TileThePlane

**Comment by TileThePlane** [comment]
@omi10859 Please see PR.
